# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='amazon_price',
        ),
        migrations.AddField(
            model_name='book',
            name='lab_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
