# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180421_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='puid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
