# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180422_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='puid',
        ),
        migrations.AddField(
            model_name='course',
            name='puid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
