# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_book_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='puid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
