# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_puid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Buyer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='authUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
