# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180425_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='authUser',
            new_name='user',
        ),
    ]
