# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180425_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Book'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Listing'),
        ),
    ]
