# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180426_2354'),
        ('app', '0010_post'),
    ]

    operations = [
    ]
