# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_text',
            field=models.BooleanField(default=False),
        ),
    ]
