# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180427_1632'),
        ('app', '0013_auto_20180426_2219'),
    ]

    operations = [
    ]
