# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20180427_1938'),
        ('app', '0014_merge_20180427_1529'),
    ]

    operations = [
    ]
