# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20180427_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
