# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
