# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.CharField(default='', max_length=100)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Listing')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
