# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20180427_1546'),
        ('app', '0022_auto_20180501_0124'),
    ]

    operations = [
    ]
