# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180501_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_from',
        ),
        migrations.AddField(
            model_name='request',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='app.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
