# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180501_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='listings',
            new_name='listing',
        ),
    ]
