# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180501_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='saved_by',
        ),
    ]
