# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180501_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='cart',
            name='saved_by',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
