# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180501_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='saved_by',
            new_name='user',
        ),
    ]
