# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20180501_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='listing',
        ),
        migrations.AddField(
            model_name='cart',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.User'),
        ),
    ]
