# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180501_1431'),
        ('app', '0030_auto_20180501_1954'),
    ]

    operations = [
    ]
