# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180501_2319'),
        ('app', '0024_auto_20180501_1431'),
    ]

    operations = [
    ]
