# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_merge_20180501_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='currentOffer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
