# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_merge_20180502_1542'),
        ('app', '0033_cart_currentoffer'),
    ]

    operations = [
    ]
