# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20180502_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
