# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20180502_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
    ]
