# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-05 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(default='', max_length=500),
        ),
    ]
