# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.TextField(),
        ),
    ]
