# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-05 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20180505_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='user',
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
