# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20180505_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='course_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
