# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_notifications_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.TextField(),
        ),
    ]
