# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20180507_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_text',
        ),
    ]
